name: ada-due-label

on:
  workflow_dispatch:
#  issues:
#    types: [opened]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "ADA Due"
